### ISSUE TITLE
Update Deployment Modules

### ISSUE THREAD

**Issue by RasmusOrsoe** [graphnet-team/graphnet#560]
As part of a push to version 2.0, we should update deployment functionality:

- [ ] Refactor deployment code to provide a general structure #539 
- [ ] Create a method for sharing pre-trained models for each experiment #546 
- [ ] Create unit tests of deployment code that tests core functionality and ensure that pre-trained models in deployment in analyses are supported #559
