### ISSUE TITLE
Deprecation List for GraphNeT 2.0

### ISSUE THREAD

**Issue by RasmusOrsoe** [graphnet-team/graphnet#647]
This thread tracks the items marked for deprecation for the release of GraphNeT 2.0.

- [ ] - ´gnn´ argument in `StandardModel`. See #646 
- [ ] - call to `rename_state_dict_entries` in `Model.load_state_dict`
- [ ] - `save_model_config` and `save_dataset_config` decorators. See #591 
- [ ] - delete `graphnet.data.parquet` and `graphnet.data.sqlite` See #659

**Comment by AMHermansen** [comment]
- [ ] - `save_model_config` and `save_dataset_config` decorators. See #591
